/*
 *  black-duck-radar
 *
 *  Copyright (c) 2019 Synopsys, Inc.
 *
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements. See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership. The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License. You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied. See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */

export const APP_UNLOAD = 'APP_UNLOAD';
export const LOAD_STATE_SET = 'LOAD_STATE_SET';
export const LOAD_STATE_DELETE = 'LOAD_STATE_DELETE';

// Set visibility state
export const FRAME_VISIBILITY_TOGGLE = 'FRAME_VISIBILITY_TOGGLE';
export const FRAME_VISIBILITY_DELETE = 'FRAME_VISIBILITY_DELETE';

export const MENU_ITEM_SELECT = 'MENU_ITEM_SELECT';
export const MENU_STATE_DELETE = 'MENU_STATE_DELETE';

export const KB_RELEASE_SYNC = 'KB_RELEASE_SYNC';
export const DISPLAY_OPTIONS_PAGE = 'DISPLAY_OPTIONS_PAGE';

// Hub Actions
export const BLACKDUCK_CONFIGURED_CHECK = 'BLACKDUCK_CONFIGURED_CHECK';
export const BLACKDUCK_BEARER_TOKEN_SET = 'BLACKDUCK_BEARER_TOKEN_SET';
export const BLACKDUCK_TOKEN_SET = 'BLACKDUCK_TOKEN_SET';
export const ARTIFACTORY_URL_SET = 'ARTIFACTORY_URL_SET';
export const HUB_LOGIN_WINDOW_OPEN = 'HUB_LOGIN_WINDOW_OPEN';
export const HUB_LOGIN_WINDOW_SET = 'HUB_LOGIN_WINDOW_SET';
export const HUB_LOGIN = 'HUB_LOGIN';
export const HUB_LOGOUT = 'HUB_LOGOUT';

export const HUB_AUTH_STATE_SET = 'HUB_AUTH_STATE_SET';
export const HUB_USERNAME_SET = 'HUB_USERNAME_SET';
export const HUB_ORIGIN_SET = 'HUB_ORIGIN_SET';

export const HUB_EXTERNAL_COMPONENT_SYNC = 'HUB_COMPONENT_SYNC';
export const HUB_EXTERNAL_COMPONENT_SET = 'HUB_COMPONENT_SET';
export const HUB_EXTERNAL_COMPONENT_DELETE = 'HUB_COMPONENT_DELETE';

export const HUB_COMPONENT_VERSION_SYNC = 'HUB_COMPONENT_VERSION_SYNC';
export const HUB_COMPONENT_VERSION_SET = 'HUB_COMPONENT_VERSION_SET';
export const HUB_COMPONENT_VERSION_DELETE = 'HUB_COMPONENT_VERSION_DELETE';

export const HUB_PROJECT_VERSION_COMPONENTS_SYNC = 'HUB_PROJECT_VERSION_COMPONENTS_SYNC';
export const HUB_PROJECT_VERSION_COMPONENTS_SET = 'HUB_PROJECT_VERSION_COMPONENTS_SET';
export const HUB_PROJECT_VERSION_COMPONENTS_DELETE = 'HUB_PROJECT_VERSION_COMPONENTS_DELETE';

export const HUB_COMPONENT_VERSION_REFERENCE_PROJECTS_SYNC = 'HUB_COMPONENT_VERSION_REFERENCE_PROJECTS_SYNC';
export const HUB_COMPONENT_VERSION_REFERENCE_PROJECTS_SET = 'HUB_COMPONENT_VERSION_REFERENCE_PROJECTS_SET';
export const HUB_COMPONENT_VERSION_REFERENCE_PROJECTS_DELETE = 'HUB_COMPONENT_VERSION_REFERENCE_PROJECTS_DELETE';

export const HUB_COMPONENT_POLICIES_SYNC = 'HUB_COMPONENT_POLICIES_SYNC';
export const HUB_COMPONENT_POLICIES_SET = 'HUB_COMPONENT_POLICIES_SET';
export const HUB_COMPONENT_POLICIES_DELETE = 'HUB_COMPONENT_POLICIES_DELETE';

export const HUB_COMPONENT_VULNERABILITIES_SYNC = 'HUB_COMPONENT_VULNERABILITIES_SYNC';
export const HUB_COMPONENT_VULNERABILITIES_SET = 'HUB_COMPONENT_VULNERABILITIES_SET';
export const HUB_COMPONENT_VULNERABILITIES_DELETE = 'HUB_COMPONENT_VULNERABILITIES_DELETE';

export const HUB_COMPONENT_RISK_PROFILE_SYNC = 'HUB_COMPONENT_RISK_PROFILE_SYNC';
export const HUB_COMPONENT_RISK_PROFILE_SET = 'HUB_COMPONENT_RISK_PROFILE_SET';
export const HUB_COMPONENT_RISK_PROFILE_DELETE = 'HUB_COMPONENT_RISK_PROFILE_DELETE';

export const CHROME_EXTENSION_DETAILS_SET = 'CHROME_EXTENSION_DETAILS_SET';

export const HUB_EXTERNAL_VULNERABILITIES_SYNC = 'HUB_EXTERNAL_VULNERABILITIES_SYNC';

export const HUB_COMPONENT_REFRESH = 'HUB_COMPONENT_REFRESH';

export const UPDATE_EXTENSION_ICON = 'UPDATE_EXTENSION_ICON';

export const FETCHING_DATA = 'FETCHING_DATA';
